# Generated by Django 6.0.3 on 2026-03-14 01:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('IZIPAY', 'Izipay (Tarjeta)'), ('TRANSFER', 'Transferencia Bancaria'), ('CASH', 'Efectivo')], max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('config', models.JSONField(default=dict, help_text='Configuración específica del método (API keys, números, etc.)', verbose_name='Configuración')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto máximo')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)')),
                ('commission_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión fija')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Por defecto?')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=50, unique=True, verbose_name='Código de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto después de comisión', max_digits=10, verbose_name='Monto neto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transacción')),
                ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de transacción')),
                ('authorization_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de autorización')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de pago')),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número de teléfono')),
                ('operation_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de operación')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='payments/vouchers/', verbose_name='Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='events.enrollment', verbose_name='Inscripción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50, verbose_name='Pasarela')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='Tipo de transacción')),
                ('gateway_transaction_id', models.CharField(max_length=100, verbose_name='ID en pasarela')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
                ('status_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de estado')),
                ('status_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de estado')),
                ('request_data', models.JSONField(default=dict, verbose_name='Datos de solicitud')),
                ('response_data', models.JSONField(default=dict, verbose_name='Datos de respuesta')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_code', models.CharField(max_length=50, unique=True, verbose_name='Código de reembolso')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto a reembolsar')),
                ('reason', models.CharField(choices=[('DUPLICATE', 'Pago duplicado'), ('CANCELLATION', 'Cancelación de curso'), ('ERROR', 'Error en el monto'), ('OTHER', 'Otro')], max_length=20, verbose_name='Motivo')),
                ('reason_text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción del motivo')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de reembolso en pasarela')),
                ('refund_date', models.DateTimeField(verbose_name='Fecha de reembolso')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSED', 'Procesado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Pago original')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_code', 'status'], name='payments_pa_payment_2fc9db_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['enrollment', 'status'], name='payments_pa_enrollm_ab85b8_idx'),
        ),
    ]
