# Generated by Django 6.0.3 on 2026-03-14 01:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('user_type', models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Personal Administrativo'), ('INSTRUCTOR', 'Instructor'), ('PARTICIPANT', 'Participante')], default='PARTICIPANT', max_length=20, verbose_name='Tipo de usuario')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASSPORT', 'Pasaporte'), ('RUC', 'RUC')], default='DNI', max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de documento inválido', regex='^\\d{8}$|^\\d{12}$|^[a-zA-Z0-9]{9,12}$')], verbose_name='Número de documento')),
                ('phone', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El número de celular debe tener 9 dígitos y comenzar con 9', regex='^9\\d{8}$')], verbose_name='Celular')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], max_length=2, null=True, verbose_name='Género')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profiles/', verbose_name='Foto de perfil')),
                ('professional_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título profesional')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialización')),
                ('biography', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Biografía profesional')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es personal?')),
                ('email_verified', models.BooleanField(default=False, verbose_name='¿Email verificado?')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='¿Teléfono verificado?')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Intentos fallidos')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones')),
                ('receive_promotions', models.BooleanField(default=False, verbose_name='Recibir promociones')),
                ('language_preference', models.CharField(default='es', max_length=10, verbose_name='Idioma preferido')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('is_used', models.BooleanField(default=False, verbose_name='¿Fue usado?')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Restablecimiento de contraseña',
                'verbose_name_plural': 'Restablecimientos de contraseña',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PROFILE_UPDATE', 'Actualización de perfil'), ('CERTIFICATE_VIEW', 'Visualización de certificado'), ('CERTIFICATE_DOWNLOAD', 'Descarga de certificado'), ('PAYMENT', 'Pago realizado'), ('COURSE_ENROLL', 'Inscripción a curso')], max_length=50, verbose_name='Tipo de actividad')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de usuario',
                'verbose_name_plural': 'Actividades de usuarios',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'document_number'], name='users_user_email_23a2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='users_user_user_ty_92c6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-timestamp'], name='users_usera_user_id_f30086_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type'], name='users_usera_activit_e23d32_idx'),
        ),
    ]
