# Generated by Django 6.0.3 on 2026-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registro de usuario'), ('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Intento de sesión fallido'), ('LOGOUT', 'Cierre de sesión'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PROFILE_UPDATE', 'Actualización de perfil'), ('CERTIFICATE_VIEW', 'Visualización de certificado'), ('CERTIFICATE_DOWNLOAD', 'Descarga de certificado'), ('PAYMENT', 'Pago realizado'), ('COURSE_ENROLL', 'Inscripción a curso')], max_length=50, verbose_name='Tipo de actividad'),
        ),
    ]
