# Generated by Django 6.0.3 on 2026-03-14 01:05

import certificates.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATE', 'Generación'), ('DOWNLOAD', 'Descarga'), ('VALIDATE', 'Validación'), ('EMAIL', 'Envío por email'), ('CANCEL', 'Anulación'), ('RENEW', 'Renovación')], max_length=20, verbose_name='Acción')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Registro de certificado',
                'verbose_name_plural': 'Registros de certificados',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código de plantilla')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('template_file', models.FileField(help_text='HTML, PDF o imagen de fondo', upload_to=certificates.models.certificate_template_path, validators=[django.core.validators.FileExtensionValidator(['html', 'pdf', 'jpg', 'png'])], verbose_name='Archivo de plantilla')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/backgrounds/', verbose_name='Imagen de fondo')),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Vertical'), ('LANDSCAPE', 'Horizontal')], default='LANDSCAPE', max_length=10, verbose_name='Orientación')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('LETTER', 'Carta'), ('LEGAL', 'Oficio')], default='A4', max_length=10, verbose_name='Tamaño de papel')),
                ('margin_top', models.FloatField(default=50, verbose_name='Margen superior (px)')),
                ('margin_bottom', models.FloatField(default=50, verbose_name='Margen inferior (px)')),
                ('margin_left', models.FloatField(default=50, verbose_name='Margen izquierdo (px)')),
                ('margin_right', models.FloatField(default=50, verbose_name='Margen derecho (px)')),
                ('name_font_size', models.IntegerField(default=48, verbose_name='Tamaño fuente del nombre')),
                ('name_font_color', models.CharField(default='#000000', max_length=20, verbose_name='Color del nombre')),
                ('name_position_x', models.FloatField(default=300, verbose_name='Posición X del nombre')),
                ('name_position_y', models.FloatField(default=400, verbose_name='Posición Y del nombre')),
                ('course_font_size', models.IntegerField(default=24, verbose_name='Tamaño fuente del curso')),
                ('course_position_x', models.FloatField(default=300, verbose_name='Posición X del curso')),
                ('course_position_y', models.FloatField(default=500, verbose_name='Posición Y del curso')),
                ('date_font_size', models.IntegerField(default=18, verbose_name='Tamaño fuente de la fecha')),
                ('date_position_x', models.FloatField(default=300, verbose_name='Posición X de la fecha')),
                ('date_position_y', models.FloatField(default=600, verbose_name='Posición Y de la fecha')),
                ('qr_size', models.IntegerField(default=100, verbose_name='Tamaño del código QR')),
                ('qr_position_x', models.FloatField(default=600, verbose_name='Posición X del QR')),
                ('qr_position_y', models.FloatField(default=500, verbose_name='Posición Y del QR')),
                ('default_text', models.TextField(default='Otorga el presente certificado a:', help_text='Texto que aparecerá antes del nombre', max_length=1000, verbose_name='Texto por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Plantilla por defecto?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de certificado',
                'verbose_name_plural': 'Plantillas de certificados',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(max_length=50, unique=True, verbose_name='Código del certificado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=certificates.models.certificate_pdf_path, verbose_name='Archivo PDF')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/', verbose_name='Código QR')),
                ('participant_name', models.CharField(max_length=200, verbose_name='Nombre del participante')),
                ('participant_document', models.CharField(max_length=20, verbose_name='Documento del participante')),
                ('course_name', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('course_duration', models.CharField(max_length=100, verbose_name='Duración del curso')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('completion_date', models.DateField(verbose_name='Fecha de culminación')),
                ('custom_text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Texto personalizado')),
                ('validation_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash de validación')),
                ('validation_url', models.URLField(max_length=255, verbose_name='URL de validación')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('GENERATED', 'Generado'), ('SENT', 'Enviado'), ('DOWNLOADED', 'Descargado'), ('VALIDATED', 'Validado'), ('CANCELLED', 'Anulado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generación')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de descarga')),
                ('downloaded_count', models.PositiveIntegerField(default=0, verbose_name='Número de descargas')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('validated_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de validación')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('cancellation_reason', models.TextField(blank=True, max_length=500, null=True, verbose_name='Motivo de anulación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
