# Generated by Django 6.0.3 on 2026-03-14 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VIEW', 'Visualización'), ('DOWNLOAD', 'Descarga'), ('EMAIL', 'Envío por email'), ('SHARE', 'Compartir')], max_length=20, verbose_name='Tipo de acceso')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=500, null=True, verbose_name='Origen')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='certificates.certificate', verbose_name='Certificado')),
            ],
            options={
                'verbose_name': 'Acceso a certificado',
                'verbose_name_plural': 'Accesos a certificados',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ValidationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash intentado')),
                ('was_successful', models.BooleanField(default=False, verbose_name='¿Fue exitoso?')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_attempts', to='certificates.certificate', verbose_name='Certificado')),
            ],
            options={
                'verbose_name': 'Intento de validación',
                'verbose_name_plural': 'Intentos de validación',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['validation_hash', 'timestamp'], name='validation__validat_153535_idx')],
            },
        ),
    ]
