# Generated by Django 6.0.3 on 2026-05-22 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Duración total (horas)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Duración (semanas)'),
        ),
    ]
