# Generated by Django 6.0.3 on 2026-05-28 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_course_cover_image_alter_course_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la lección')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duración (minutos)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='¿Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='events.coursemodule', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
